# Network Settings

# Mengatur alamat IP interface agar Redis dapat menerima koneksi jaringan luar.
bind 0.0.0.0

# Port TCP utama yang digunakan oleh Redis server.
port 6379

# Mode proteksi bawaan untuk mencegah akses tanpa izin dari jaringan publik.
protected-mode yes

# Logging

# Menentukan jalannya proses. 'no' membuat Redis tetap berjalan interaktif di foreground,
# yang sangat disarankan saat dijalankan di dalam container Docker/Kubernetes.
daemonize no

# Lokasi penyimpanan catatan log aktivitas.
# Diisi string kosong ("") agar log dikirim ke stdout/console untuk kemudahan pemantauan.
logfile ""

# Tingkat filter informasi log. 'notice' mencatat event penting dan kondisi operasional normal.
loglevel notice

# Persistence

# RDB berfungsi menyimpan snapshot data ke disk secara periodik.
# Format: save <detik> <jumlah_perubahan_key>
save 3600 1
save 300 100
save 60 10000

# AOF (Append Only File) berfungsi mencatat setiap operasi penulisan data untuk daya tahan maksimal.
appendonly yes

# Kenapa menggunakan AOF? Karena AOF lebih aman dibandingkan RDB, terutama untuk mencegah kehilangan data saat Redis crash. AOF mencatat setiap perintah yang mengubah data, sehingga memungkinkan pemulihan data yang lebih lengkap.

# Alasan Redis baca AOF duluan pas startup itu karena datanya paling utuh atau lengkap hingga detik terakhir. Tapi, RDB juga berguna untuk mempercepat proses pemulihan data saat restart. Penggunaan keduanya memberikan efek booting cepat dan kita tidak perlu khawatir kehilangan data pada beberapa detik terakhir.

# Frekuensi penulisan AOF ke disk. 'everysec' memberikan keseimbangan ideal antara performa dan keamanan.
appendfsync everysec

# Memory Management

# Batas maksimal penggunaan memori RAM (contoh: 100 Megabyte).
maxmemory 100mb

# Strategi penghapusan data saat kapasitas RAM penuh.
# allkeys-lru akan menghapus data yang paling lama tidak diakses atau digunakan berdasarkan waktu akses terakhir.
# allkeys-lfu akan menghapus data yang paling jarang diakses berdasarkan jumlah frekuensi/jumlah akses.
# allkeys-lrm sama dengan lru, tetapi lrm tidak mengeksekusi berdasarkan kapan dibaca tetapi akan menghapus key yang paling lama tidak diubah/dimodifikasi
maxmemory-policy allkeys-lru

# User Management
# Mematikan user bawaan 'default' agar tidak ada koneksi tanpa autentikasi yang bisa masuk
user default off

# User admin 'redisman' dengan akses penuh (+@all), password 'superman', dan akses ke semua key (~:*) serta channel (&:*). Jadi user redisman mendapatkan hak akses penuh (Superadmin). 
user redisman on >superman ~:* &:* +@all

# Pengguna terbatas untuk kebutuhan aplikasi spesifik
# User nicohondo dengan hak akses terbatas:
# - Password: hondo1234
# - Hanya bisa akses key yang diawali 'nicohondo:*'
# - Hapus hak akses ke channel (resetchannels)
# - Perintah yang diizinkan hanya grup string (+@string), ping (+ping), dan delete (+del)

user nicohondo on >hondo1234 resetchannels ~nicohondo:* +@string +ping +del